version: "3"

services:
  app:
    build:
      context: node
    container_name: app    
    entrypoint: bash -c "npm install && dockerize -wait tcp://db:3306 -timeout 20s node index.js"
    restart: always
    volumes:
      - ./node:/usr/src/app      
    tty: true
    networks:
      - node-network
    depends_on:            
      - db    

  nginx:
    build:
      context: nginx      
    container_name: nginx
    ports:
      - "8080:80"
    networks:
      - node-network 
    depends_on:      
      - app    

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:      
      - ./mysql:/var/lib/mysql
      - ./node/initdb:/docker-entrypoint-initdb.d/
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306
    networks:
      - node-network   

networks:
  node-network:
    driver: bridge